server:
  port: 8082

spring:
  application:
    name: analysis-service
  datasource:
    url: jdbc:postgresql://analysis-db:5432/analysis_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
