server:
  port: 8081

spring:
  application:
    name: file-service
  datasource:
    url: jdbc:postgresql://file-db:5432/file_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  upload-dir: /uploads
  analysis-service-url: http://analysis-service:8082/api/internal/analysis
